### ISSUE TITLE
ThE Role Assignment Already Exists patientandpopulationservices-smartonfhir-oncg10

### ISSUE THREAD

**Issue by muthink** [Azure-Samples/azure-health-data-and-ai-samples#197]
While running azd up, after some time during the creating/updating resources stage, the following error is thrown: with the patientandpopulationservices-smartonfhir-oncg10 sample.
  
  You can view detailed progress in the Azure Portal:
  https://portal.azure.com/#view/HubsExtension/DeploymentDetailsBlade/~/overview/id/%2Fsubscriptions%2Fa0013bff-81a8-4606-bbc9-2df00694ec35%2Fproviders%2FMicrosoft.Resources%2Fdeployments%2Ffhir-1715196305

  |==     | Creating/Updating resources
ERROR: error executing step command 'provision': deployment failed: failing invoking action 'provision', error deploying infrastructure: deploying to subscription:

Deployment Error Details:
RoleAssignmentExists: The role assignment already exists.

TraceID: 014e73cb1dd725bb36a094bacfa8df14

**Comment by muthink** [comment]
Any ideas how this happens?

**Comment by evachen96** [comment]
Hi @muthink  - thanks for submitting your issue. We have double checked if the same guid is used as the unique id for 'user.all.all' and 'user.all.read' in app-roles.json. However, it is not the same in the repository. If these ids are the same, the error (Duplicate 'id' values are present in the 'appRoles' values.) should occur when updating the manifest json for the FHIR resource app, not when deploying the application.

We're also unable to reproduce this issue. Are you still having this problem? If so, can you share what steps you took to get this issue>

- Are you redeploying the sample?
- If so, then are you using the same directory from where that application was deployed? Is there any change that you made in the deployed resources or anything other than mentioned in the documentation?
- Can we get steps you did so that we can try to repro?
- Are you able to share error logs to determine where/when the resource deployment fails and for which role assignment? We are currently unable to access the link above that you shared. 

Thanks!

**Comment by evachen96** [comment]
Closing this issue as we haven't heard back. Please feel free to reopen or submit a new issue if the issue still arises!
