### ISSUE TITLE
Compartments in Azure health data services.

### ISSUE THREAD

**Issue by Kedar782** [Azure-Samples/azure-health-data-and-ai-samples#198]
I'm using Azure Health Data Services for ONC g 10 certification.

I have many clients using our EMR and each client has their own database in sql server.

I want to migrate all of data from sql server into Azure Health Data Services.

Do we need to create separate Azure Health Data Service for each client? We want clients data unique to themselves others cannot access it.

Can we do this using only one Azure Health Data Service?

I will really appreciate your help on this.

Thanks in advanced!

**Comment by evachen96** [comment]
Hi @Kedar782  - Steve answered this over email, copying here in case others have the same question: 

This depends on if you have to physically separate data (i.e. you cannot co-mingle data in the same physical data store due to security or compliance reasons). If this is a requirement you would need separate instances of the FHIR Service.  If you can co-mingle data physically you could use a tagging strategy on the resources. This is accomplished by adding a tag to each resources on commit to the FHIR Service that identifies the owner of the data, then when querying data you would add the owner tag to every query as a pre-processing request. The tag would also become a part of your export filters as well....Both of these options would employ an instance of API Management service which would provide you a single FHIR endpoint that can intercept requests/responses to either ensure owner tagging on the way in and filtering on the way out of  the FHIR Store, or route the request to the correct FHIR Instance to persist the data.
